image: gitpod/workspace-full

tasks:
  - init: |
      npm install
      curl https://cli-assets.heroku.com/install.sh | sh
    command: node src/server.js

ports:
  - port: 3000
    onOpen: open-preview
